'use strict';
const nav=document.getElementById('nav');
window.addEventListener('scroll',()=>nav?.classList.toggle('scrolled',window.scrollY>50),{passive:true});
const revObs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revObs.unobserve(e.target)}})},{threshold:.1,rootMargin:'0px 0px -40px 0px'});
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.reveal:not(.visible)').forEach(el=>revObs.observe(el))});
function animateCounter(el){const t=parseInt(el.dataset.target,10),s=el.dataset.suffix||'';let c=0;const st=t/(1800/16),tmr=setInterval(()=>{c+=st;if(c>=t){c=t;clearInterval(tmr)}el.textContent=Math.floor(c)+s},16)}
const cntObs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){animateCounter(e.target);cntObs.unobserve(e.target)}})},{threshold:.5});
document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('.stat__num[data-target]').forEach(el=>cntObs.observe(el)));
function lazyLoadImages(root){const imgs=(root||document).querySelectorAll('img[data-src]');if('IntersectionObserver' in window){const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){const img=e.target;img.src=img.dataset.src;img.onload=()=>img.classList.add('loaded');obs.unobserve(img)}})},{rootMargin:'300px'});imgs.forEach(img=>obs.observe(img))}else imgs.forEach(img=>{img.src=img.dataset.src;img.onload=()=>img.classList.add('loaded')})}
document.addEventListener('DOMContentLoaded',()=>lazyLoadImages());
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'})}});
const burger=document.getElementById('navBurger');let mMenu=null;
burger?.addEventListener('click',()=>{if(mMenu){mMenu.remove();mMenu=null;return}mMenu=document.createElement('div');mMenu.style.cssText='position:fixed;top:62px;left:0;right:0;background:rgba(26,16,10,.98);backdrop-filter:blur(16px);padding:1.5rem 2rem;z-index:199;border-bottom:1px solid rgba(196,118,74,.2);animation:slideDown .25s ease both';const base=location.pathname.includes('/pages/')?'..':'';mMenu.innerHTML=[['nav_nosotros',`${base}/index.html#nosotros`],['nav_catalogo',`${base}/pages/catalogo.html`],['nav_artesanos',`${base}/pages/artesanos.html`],['nav_mercados',`${base}/index.html#mercados`],['nav_contacto',`${base}/pages/contacto.html`]].map(([k,h])=>`<a href="${h}" style="display:block;font-family:Outfit,sans-serif;font-size:.95rem;font-weight:500;letter-spacing:.08em;text-transform:uppercase;color:rgba(242,232,217,.8);padding:.85rem 0;border-bottom:1px solid rgba(196,118,74,.1)" data-i18n="${k}">${(window.t&&window.t(k))||k}</a>`).join('')+`<div style="display:flex;gap:.75rem;margin-top:1.25rem"><a href="${base}/pages/login.html" style="flex:1;text-align:center;padding:.75rem;border:1px solid rgba(242,232,217,.25);color:rgba(242,232,217,.8);border-radius:4px;font-family:Outfit,sans-serif;font-size:.8rem;font-weight:600;text-transform:uppercase" data-i18n="nav_login">Ingresar</a><a href="${base}/pages/register.html" style="flex:1;text-align:center;padding:.75rem;background:#C4764A;color:#FEFCF8;border-radius:4px;font-family:Outfit,sans-serif;font-size:.8rem;font-weight:600;text-transform:uppercase" data-i18n="nav_register">Registrarse</a></div>`;document.body.appendChild(mMenu);if(window.applyTranslations)applyTranslations()});
window.openArtisanModal=function(data){const o=document.getElementById('artisanModal');if(!o)return;o.querySelector('.modal__img img').src=data.img;o.querySelector('.modal__tag').textContent=data.tag;o.querySelector('.modal__body h2').textContent=data.name;o.querySelector('.modal__village').textContent='◎ '+data.village;const ps=o.querySelectorAll('.modal__para');ps[0].textContent=data.bio;ps[1].textContent=data.story;const ms=o.querySelectorAll('.modal__metric');data.metrics.forEach((m,i)=>{if(ms[i]){ms[i].querySelector('strong').textContent=m.value;ms[i].querySelector('span').textContent=m.label}});o.querySelector('.modal__tags').innerHTML=data.products.map(p=>`<span class="modal__tag-item">${p}</span>`).join('');o.classList.add('open');document.body.style.overflow='hidden'};
window.closeArtisanModal=function(){document.getElementById('artisanModal')?.classList.remove('open');document.body.style.overflow=''};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeArtisanModal()});
